trigger:
  branches:
    include:
      - main  # Trigger on changes to the main branch

pool: satishpool

resources:
  repositories:
    - repository: common  # Local name to reference the repository
      type: git           # Type of repository
      name: motorola/infrapipeline  # Project and repository name
      ref: refs/heads/main  # Reference to the main branch

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
